version: "3.8"

services:
  nginx:
    image: nginx:stable
    container_name: nginx_test
    restart: unless-stopped
    ports:
      - "${PROJECT_PORT}:80"
    volumes:
      - ./project:/var/www/html
      - ./docker//vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker//logs/nginx:/var/log/nginx/
    depends_on:
      - app
    networks:
      - test_network

  app:
    build:
      context: ./docker
      dockerfile: dockerfiles/php.Dockerfile
    container_name: app_test
    restart: unless-stopped
    volumes:
      - ./project:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - test_network

  db:
    image: mariadb:10.5
    container_name: db_test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
