CREATE TABLE b_weather_data
(
    ID          INT(11) NOT NULL AUTO_INCREMENT,
    CITY        VARCHAR(255) NOT NULL,
    TEMPERATURE FLOAT        NOT NULL,
    HUMIDITY    INT(11) NOT NULL,
    TIMESTAMP   DATETIME     NOT NULL,
    PRIMARY KEY (ID)
);